# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e108422bb75267c98520ce6dbccd1688fb85f5eb8190d3ef98514acf99d0cab123934edaef39cac78142287282c8c1e7aa56ba0f4fc11c7f6388c17ac1705fd1

test:
  secret_key_base: b5c8c114be2f73eb48bc876f47f02b1181ce3d21540f5db55677bfd5a98719942f2c376c0d93935620418e69941909bb958796434ce93c46a4468c1d546bc04d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
